name: e-commerce
services:
  app:
    depends_on:
      - database
    image: ghcr.io/m-t-e-k-u-g-r/e-commerce:latest
    build: .
    environment:
      PROFILE: production
      DB_HOST: database
      DATABASE: ${DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads

  database:
      image: postgres:18-alpine
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DATABASE}
      ports:
        - "5432:5432"
      volumes:
        - data:/var/lib/postgresql/docker

volumes:
  data:
