spring:
    datasource:
        url: ${DB_URL}
        driver-class-name: org.postgresql.Driver
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: validate
    profiles:
        active: ${PROFILE:development}
    web:
        error:
            include-message: always

jwt:
    refresh-token-secret: ${REFRESH_TOKEN_SECRET}
    access-token-secret: ${ACCESS_TOKEN_SECRET}

server:
    servlet:
        context-path: /api

logging:
    level:
        org:
            springframework:
                web: ${LOG_LEVEL:error}
            hibernate:
                sql: ${LOG_LEVEL:error}