name: Deployment
on:
  push:
    tags:
      - "*.*.*"
    paths:
      - "frontend/**"
      - "backend/**"
env:
  IMAGE: ghcr.io/m-t-e-k-u-g-r/e-commerce
jobs:
  deploy-app:
    name: Deploy Application
    runs-on: ubuntu-latest
    environment: env
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: ./.github/actions/ghcr-login
        with:
          token: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: ./.github/actions/build-n-push
        with:
          image: ${{ env.IMAGE }}
          context: .